services:
  web:
    build:
      context: ./bia_proj
      dockerfile: Dockerfile.prod
    command: "gunicorn bia_proj.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      ./.env.prod
    depends_on:
      - db
    volumes:
      - static_files:/home/bia/web/staticfiles

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

volumes:
  postgres_data:
  static_files:
