services:
  web:
    build: ./bia_proj
    command: "python manage.py runserver"
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - brew_it_again_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.dev

volumes:
  brew_it_again_postgres_data:
