# Generated by Django 5.0.6 on 2024-07-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeerecipeentry',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
