# Generated by Django 5.0.6 on 2024-07-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bia', '0002_alter_coffeerecipeentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeerecipeentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
