# Generated by Django 5.0.6 on 2024-08-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bia', '0003_alter_coffeerecipeentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeerecipeentry',
            name='grams_coffee',
            field=models.FloatField(max_length=12),
        ),
        migrations.AlterField(
            model_name='coffeerecipeentry',
            name='mili_water',
            field=models.FloatField(max_length=12),
        ),
    ]
